### DISCUSSION TITLE
How can I animate a slide open/slide close of the Dropdown-menu element?

### DISCUSSION THREAD

**Discussion by laurenzcodes** [fraserxu/react-dropdown#217] [Q&A]
Hello there,

I want to animate the dropdown closing and opening. My current approach is as follows:

```css
.is-open .Dropdown-menu {
      max-height: 300px;
}

 .Dropdown-menu {
      transition: max-height 300ms ease-in-out;
      max-height: 0px;
      overflow: hidden;
}
```

In theory, this should transition the height of the element onLoad, but it still just pops in instantly.
Any help or suggestion would be apprechiated.
