### ISSUE TITLE
Dropdown option

### ISSUE THREAD

**Issue by DenysPavlenko** [fraserxu/react-dropdown#228]
Hello, 
I am using tailwind css and it is pretty much easy to customize the dropdnow. I can change everything accept for Dropdown-option class. It would be great to add such property to the component.

**Comment by rayhaanDev** [comment]
A work-around for the time being that I have found is simply just targeting the class selector for dropdown items. E.g.
```scss
./* Style all dropdown options */
.Dropdown-option {
  //styles-here
}

/* Style the option that is currently selected */
.Dropdown-option.is-selected {
  background-color: //some-background-color
}

/* Add a hover effect for options */
.Dropdown-option:hover {
  background-color: //some-background-color
}
```
