### ISSUE TITLE
OnClick seems to be on the text rather than the div making it imperfect and unusable 

### ISSUE THREAD

**Issue by peterdoane** [fraserxu/react-dropdown#72]
I like the way it looks but I am not able to get it approved because if I click anywhere around the edges it does not select. If I was able to put it on the div rather than the text label in the dropdown i believe this would fix this

**Comment by zachgibson** [comment]
You should be able to set CSS properties to fix this. e.g.
```css
.Dropdown-root {
    position: relative;
}

.Dropdown-control {
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
}
```

Doing this will make the entire dropdown box (select) clickable instead of only the text.
